management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: kroconails
    description:
    author: Sergey
    version: '@project.version@'
spring:
  profiles:
    active: dev
